CREATE DATABASE RFChain;
CREATE TABLE RFChain.TagDB (  
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `tagID` VARCHAR(64) NOT NULL,  
  `b` VARCHAR(256) NOT NULL,
  `reader` int(10) NOT NULL,
  `timestamp` DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UC_TagDB UNIQUE (id, tagID)
);
CREATE USER 'user'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON RFChain.TagDB TO 'user'@'%';
FLUSH PRIVILEGES;